name: Deploy
description: "ArgoCD based deploy action. Requires kustomize to run."

inputs:
  environment:
    required: true
    description: "Environment to deploy to, e.g. staging, production."
  version:
    required: true
    description: "Container image tag being deployed, e.g. a commit SHA."
  deploying_repo:
    required: true
    description: "List of image repositories (image names) being deployed."
  infra_repo:
    required: true
    description: "Repository for ArgoCD to pick up changes from."
  infra_branch:
    required: true
    description: "Branch in infra_repo for ArgoCD to pick up changes from."
    default: "main"
  github_app_private_key:
    required: true
    description: "Private key of a Github App that has Repository Content Read & Write access to the infra repo."
  github_app_id:
    required: true
    description: "App ID of a Github App that has Repository Content Read & Write access to the infra repo."
  app:
    required: true
    description: "ArgoCD application to be deployed."
  argocd_pipeline_password:
    required: true
    description: "Password for the `pipeline` user in ArgoCD (read-only permissions for such user are sufficient)."
  argocd_server:
    required: true
    description: "Host name of the server where ArgoCD runs, e.g. argocd.example.com"
  argocd_sync_timeout:
    required: false
    default: "120"
    description: "Timeout applied to the argocd sync trigger"

runs:
  using: "composite"
  steps:
    - name: "Create GitHub App token"
      uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ inputs.github_app_id }}
        private-key: ${{ inputs.github_app_private_key }}
        owner: digitalservicebund
        repositories: ${{ inputs.infra_repo }}
    - name: "Checkout infra repository"
      uses: actions/checkout@v6
      with:
        repository: digitalservicebund/${{ inputs.infra_repo }}
        ref: ${{ inputs.infra_branch }}
        token: ${{ steps.app-token.outputs.token }}
    - name: "Update image tag for ${{ inputs.environment }}"
      env:
        DEPLOYING_REPOS: ${{ inputs.deploying_repo }}
      shell: bash
      run: |
        set -ex
        cd manifests/overlays/${{ inputs.environment }}
        IFS=,
        for repo in $DEPLOYING_REPOS
        do
          kustomize edit set image ghcr.io/digitalservicebund/${repo}:${{ inputs.version }}
        done
    - name: "Get GitHub App User ID"
      shell: bash
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - name: "Git Config"
      shell: bash
      run: |
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
    - name: "Commit an push changes to infra repo"
      shell: bash
      run: |
        git add manifests/overlays/${{ inputs.environment }}/kustomization.yaml
        git diff-index --cached --quiet HEAD ||
          git commit -m "Bump ${{ inputs.environment }} image to ${{ inputs.version }}" -m "[skip ci]" &&
          git push origin ${{ inputs.infra_branch }}
    - name: "Determine ArgoCD version"
      id: argocd-version
      shell: bash
      run: |
        set -ex
        argocd_version=$(curl -s https://${ARGOCD_SERVER}/api/version | jq -r '.Version | split("+")[0]')
        echo "version=$argocd_version" >> $GITHUB_OUTPUT
      env:
        ARGOCD_SERVER: ${{ inputs.argocd_server }}
    - name: "Cache argocd executable"
      id: cache-argocd
      uses: actions/cache@v5
      with:
        path: argocd
        key: ${{ steps.argocd-version.outputs.version }}-argocd
    - name: "Download argocd executable"
      if: steps.cache-argocd.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -ex
        curl -sSL -o argocd "https://github.com/argoproj/argo-cd/releases/download/${{ steps.argocd-version.outputs.version }}/argocd-linux-amd64"
    - name: "Trigger Argo CD sync"
      shell: bash
      run: |
        set -ex
        chmod +x argocd
        ./argocd login ${ARGOCD_SERVER} --username pipeline --password ${{ inputs.argocd_pipeline_password }} --grpc-web
        ./argocd app wait ${{ inputs.app }} --sync --timeout ${{ inputs.argocd_sync_timeout }} --grpc-web
        ./argocd app get --refresh ${{ inputs.app }} --grpc-web > /dev/null
        ./argocd app wait ${{ inputs.app }} --sync --health --timeout ${{ inputs.argocd_sync_timeout }} --grpc-web
      env:
        ARGOCD_SERVER: ${{ inputs.argocd_server }}
